### ISSUE TITLE
Investigate into Must* methods

### ISSUE THREAD

**Issue by mxschmitt** [playwright-community/playwright-go#103]
Handling the error each time is not nice, it might make sense to add or generate Must* methods which panic if an error gets returned.

**Comment by AngangGuo** [comment]
I think it's a nice to have feature for new users to try the project, but not a **MUST** feature we need.
If I wait for a button to show out and got an error, I need to see what's wrong with it and can't simply panic and suppose the job is done.
Maybe a generic `MustXXXX` func can be a wraper for anyone who need it. But until the generic is available, one can write some simple MustXXX  functions themselves. This can simplify the API maintenance.

**Comment by kumaraditya303** [comment]
I think this is useful feature and we should have it, it will simplify in testing scenario where if something goes wrong the test must be stopped with panic rather than the user handling the error.
It can be autogenerated so there is little maintenance burden.
