### ISSUE TITLE
PageWaitForRequestOptions and PageWaitForResponseOptions are not used anywhere 

### ISSUE THREAD

**Issue by sagikazarmark** [playwright-community/playwright-go#124]
The above mentioned types don't seem to be used in their respective function calls (WaitForRequest and WaitForResponse).

Looking at the code [here](https://github.com/mxschmitt/playwright-go/blob/de638a4c485a9853c489991f51d3463a9ece7126/page.go#L336) confirms that there is no way to set the timeout for those methods (other than setting the default page timeout).

**Comment by ninadingole** [comment]
It is correctly reported, the `intefaces.json` has following definition for the method [WaitFoRequest](https://github.com/ninadingole/playwright-go-fork/blob/1b26f7a64e3a2cbadd94ca3b25ed9f424ce0ccb4/scripts/data/interfaces.json#L1318) and [WaitForResponse](https://github.com/ninadingole/playwright-go-fork/blob/1b26f7a64e3a2cbadd94ca3b25ed9f424ce0ccb4/scripts/data/interfaces.json#L1322). The typescription version takes the second argument for timeout [here](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/client/page.ts#L371). This would require a fix on the go-implementation side
