### ISSUE TITLE
WaitForFunction not waiting

### ISSUE THREAD

**Issue by SamHennessy** [playwright-community/playwright-go#215]
**Expect:** `WaitForFunction` will stop the execution of my code until the statement is true or the timeout is exceeded. 

**Got:** It doesn't wait and execution continues on right away

**Version:** 1.14 and master

I've created a simple test trying to use code from the projects. 

Sorry if I've not understood how to use the features.

### Example:

Here is what I have:

```
package page_test

import (
	"fmt"
	"log"
	"testing"
	"time"

	"github.com/mxschmitt/playwright-go"
)

func assertErrorToNilf(message string, err error) {
	if err != nil {
		log.Fatalf(message, err)
	}
}

func TestWait(t *testing.T) {
	pw, err := playwright.Run()
	assertErrorToNilf("could not launch playwright: %w", err)
	browser, err := pw.Chromium.Launch()
	assertErrorToNilf("could not launch Chromium: %w", err)
	context, err := browser.NewContext()
	assertErrorToNilf("could not create context: %w", err)
	pwpage, err := context.NewPage()
	assertErrorToNilf("could not create page: %w", err)
	_, err = pwpage.Goto("https://httpbin.org/get")
	assertErrorToNilf("could not goto: %w", err)

	now := time.Now()

	_, err = pwpage.Evaluate(`() => setTimeout(() => window.FOO = true, 2000)`)
	if err != nil {
		t.Fatal(err)
	}

	_, err = pwpage.WaitForFunction(`window.FOO === true`, nil)
	if err != nil {
		t.Fatal(err)
	}

	fmt.Println(time.Now().Sub(now))

	assertErrorToNilf("could not close browser: %w", browser.Close())
	assertErrorToNilf("could not stop Playwright: %w", pw.Stop())
}
```

### Result:

```
 go test
2021/10/13 22:59:10 Downloading browsers...
2021/10/13 22:59:10 Downloaded browsers successfully
23.044054ms
PASS
ok  	github.com/SamHennessy/hlive/browser_testing/page	3.951s
```

**Comment by mxschmitt** [comment]
Its expected that it does not wait, setTimeout does not wait, it does only execute the callback at given amount of milliseconds.
What you could do, is return a promise which will resolve once the timeout has reached. Whats the reason for that you want to wait 2000ms?

**Comment by SamHennessy** [comment]
@mxschmitt thank you for your reply. The `setTimeout` is not the part that should wait. That was copied from code in the repo to make a simple example. I don't need to wait 2000ms; it's only used to illustrate the issue clearly. My actual use case is a system test where I have an asynchronous call happening over a web socket that I need to wait to complete before looking for a value on the page.
