### ISSUE TITLE
[Bug/issue] Allow specifying browser/playwright output/error stream

### ISSUE THREAD

**Issue by nmiculinic** [playwright-community/playwright-go#226]
Playwright always writes to stdout/err which isn't always desirable in the test scenario. I'd like to be able to specify which `io.Writer` playwright does write to.

See also https://github.com/onsi/ginkgo/issues/851#issuecomment-953474491  issue this is causing with ginkgo v2 parallel tests.

**Comment by kumaraditya303** [comment]
@onsi Feel free to create a PR

**Comment by onsi** [comment]
hey, sorry for the delay here - looks like I won't be able to squeeze this in any time soon - so didn't want to leave folks hanging.
