### ISSUE TITLE
Release v1.16 

### ISSUE THREAD

**Issue by kumaraditya303** [playwright-community/playwright-go#228]
Tracking issue for releasing v1.16 

- [x] https://github.com/mxschmitt/playwright-go/pull/224
- [x] https://github.com/mxschmitt/playwright-go/pull/232
- [x] https://github.com/mxschmitt/playwright-go/pull/231

**Comment by mxschmitt** [comment]
Can we also add locators?

**Comment by kumaraditya303** [comment]
> Can we also add locators?

@mxschmitt  Can you help in implementing it ?
