### ISSUE TITLE
How to Enable Trace Viewer

### ISSUE THREAD

**Issue by alecmerdler** [playwright-community/playwright-go#244]
Playwright supports a very useful looking feature called tracing, including a [GUI viewer](https://playwright.dev/docs/trace-viewer/). It isn't clear how to enable tracing using this wrapper library. There is a `TracesDir` which can be passed to the browser launch options, but no other configuration.

**Comment by mxschmitt** [comment]
Sorry for the late reply. Tracing is included see the following test: https://github.com/playwright-community/playwright-go/blob/v0.2000.0/tests/tracing_test.go

**Comment by shepherdjerred** [comment]
There are two kinds of traces:

1. Low-level Chromium traces which are useful to browser developers
2. Playwright traces that the original issue is referring to

It seems that playwright-go supports only the first which are not particularly useful.

See: https://github.com/playwright-community/playwright-go/blob/2fb5d39fa07a0a9e327224d0b23513a64bce0668/generated-interfaces.go#L186-L195

**Comment by canstand** [comment]
```go
browserContext.Tracing().Start(playwright.TracingStartOptions{
		Screenshots: playwright.Bool(true),
		Snapshots:   playwright.Bool(true),
	})

browserContext.Tracing().StartChunk()
// do something
...

// save trace to zip file
browserContext.Tracing().StopChunk("/tmp/trace.zip")
```

View trace
`playwright show-trace /tmp/trace.zip`

<img width="866" alt="Trace Viewer" src="https://github.com/playwright-community/playwright-go/assets/70889873/50bad95a-f568-49e4-8e44-cc801268d0b0">

**Comment by shepherdjerred** [comment]
Wow, thanks so much for the quick response! I tried this out and it worked.

I really appreciate the work you've put into maintaining this repository, and being so helpful in issues.
