### ISSUE TITLE
BrowserType Connect

### ISSUE THREAD

**Issue by Chimerax2** [playwright-community/playwright-go#246]
Hi i saw your thread on the node playwright and i see here it has connect option too but the options are unclear to me on how we can connect it.

I want to launch chromium via terminal and then connect playwright to it, but the connect option gets url and some other options. How will it identify to which window i want to pair it to ? 

At the moment when i use it i get `could not start websocket connection: could not connect to websocket: malformed ws or wss URL` as an error from the Connect function

**Comment by octoper** [comment]
Hello,
When you are starting chromium on your terminal you will get a WebSocket url like this
![Screen Shot 2022-03-12 at 04 55 04](https://user-images.githubusercontent.com/6823226/158001087-6caed59a-c857-4d2e-9e9a-a6238fe4326a.png)

If you take this and put it in the url option the playwright will connect.

**Comment by mxschmitt** [comment]
thanks @octoper, this is correct.
