### ISSUE TITLE
Should I defer page.Close(), browser.Close(), pw.Stop() etc?

### ISSUE THREAD

**Issue by Av1shay** [playwright-community/playwright-go#247]
Hi,
I can see in your docs that you never defering the close/stop calles (browser.Close(), pw.Stop(), page.Close(), etc)
But what if I use playwright not in a one-time script, but as part of a server process, and there is an error before calling browser.Close() for example, can't it cause memory leaks?
In particular, what if I download a file and not closing the browse context (error occurred before reaching the end of the function)? the file and the download artifacts won't delete?
Should I defer those calls?

**Comment by ryanbrainard** [comment]
I came looking for exactly this question. Anyone know? 

Similarly, it's also unclear what can be safely shared in parallel tests. For example, should there be just one Playwright instance for whole suite and shares by runs, or each create their own and stop when done?

**Comment by mxschmitt** [comment]
@Av1shay

When closing a browser, it automatically closes the contexts and pages. Also Playwright.Close will automatically close everything below it.

Yes it is correct, that if you don't close the browser or Playwright before an error happens, it can cause memory leaks while the Go executable stays alive.

in your particular example the browser context -> tab with its pages stays open and the temporary artifacts stay on the disk. So yes, you have to close the Playwright or Context instance depending on your needs.

@ryanbrainard Playwright for Go claims to be not thread-safe. I'd if you want to do stuff in parallel create multiple Playwright instances, thats what we do in Python, Java, or .NET.
