### ISSUE TITLE
mac high sierra go-jose.V2@ error

### ISSUE THREAD

**Issue by okofishe** [playwright-community/playwright-go#250]
Hello,
Why am i getting this error on mac high sierra 👎 
# cd .; git clone -- https://gopkg.in/square/go-jose.v2 /Users/user/Documents/OneDrive/golib/src/gopkg.in/square/go-jose.v2
Cloning into '/Users/user/Documents/OneDrive/golib/src/gopkg.in/square/go-jose.v2'...
fatal: unable to access 'https://gopkg.in/square/go-jose.v2/': SSL certificate problem: certificate has expired
package gopkg.in/square/go-jose.v2: exit status 128

**Comment by mxschmitt** [comment]
This is not related to this library.
