### ISSUE TITLE
Using page.route

### ISSUE THREAD

**Issue by okofishe** [playwright-community/playwright-go#252]
Hello,
How do i use page.route to block images from loading using playwright-go. The internet is full of code samples in javascript only
Any response will be highly appreciated
Thanks

**Comment by kcinnxy** [comment]
Bump

**Comment by octoper** [comment]
Hello,
You can block images by adding something like the code below before your `page.Goto`

```go
page.Route("**/*", func(route playwright.Route, request playwright.Request) {
	if request.ResourceType() == "image" {
		route.Abort("aborted")
	} else {
		route.Continue()
	}
})
```

**Comment by mxschmitt** [comment]
thanks @octoper, this is correct.

**Comment by kcinnxy** [comment]
Thanks!
