### ISSUE TITLE
Har recording option not available with Go wrapper

### ISSUE THREAD

**Issue by vincentBoyer1** [playwright-community/playwright-go#253]
Hi,
Currently, I use the Python version of Playwright but, I would like migrate to the Go version. My program uses the .HAR recording implemented in the JS and Python versions (record_har_path option in the context initialization for the Python wrapper). It seems this feature is not implemented in the Go wrapper. Is it True ? If yes, do you will add this opton in the near future or not ?
Thanks

**Comment by mxschmitt** [comment]
Closing this since it seems done now!
