### ISSUE TITLE
Can I choose network interface ? 

### ISSUE THREAD

**Issue by KMACEL** [playwright-community/playwright-go#266]
Hi. My operating system is Ubuntu. I want to use Firefox. But I have more network interface.  wlp0, eth0, wwan0 etc. I want to choose any one. I can doing it with go http.Transport->Dial. But I couldn't found any way for your lib. Could you help me ?

**Comment by mxschmitt** [comment]
This is not directly related to playwright-go code, more the way how browsers will choose the network interface.

The easiest would be to probably use a proxy server in between.e

**Comment by KMACEL** [comment]
Thank you for reply. I will write to proxy server with "github.com/elazarl/goproxy".
