### ISSUE TITLE
Question: Is it possible to refresh the DOM after Javascript elements are loaded?

### ISSUE THREAD

**Issue by supercom32** [playwright-community/playwright-go#269]
Hi there,

I have a specific edge-case where some web elements I want to select are loaded in dynamically via Javascript. However, when I try to use an xPath to obtain the element, it returns 'nil' since it was loaded in after the fact. Waiting for the page to finish loading doesn't work, since regardless of how long you wait, it appears Playwright doesn't see the updated DOM.

Is it possible to somehow refresh the DOM so that Playwright can see the page just like the user can? Or a workaround which will allow you to obtain elements which are dynamically loaded in? Using the developer console and entering my selector works just fine. Just that Playwright can't seem to find it regardless of what I do.

Thanks!

**Comment by mxschmitt** [comment]
Seems like either you need to use Page.WaitForSelector to wait for the element to appear on the DOM or you use Locators with Page.Locator("...").Click() which automatically waits for the element to appear.

Its not directly clear to me if you are using Page.QuerySelector/All but it sounded like that (not recommended anymore).

**Comment by supercom32** [comment]
Hi,

Thanks for the kind advice. In fact I am using `Page.QuerySelector`. Specifically because I tried finding `Page.Locator` but it doesn't seem to show up as a selectable method. Perhaps this functionality is a recent development and I need to update my version of playwright-go to get it? That would certainly explain things!

**Comment by mxschmitt** [comment]
Yes, its very new but should be available via go get >= [v0.2000.1](https://pkg.go.dev/github.com/playwright-community/playwright-go@v0.2000.1)

**Comment by supercom32** [comment]
Ah thanks, that would explain it. I usually lock on to a specific version of libraries (like playwright-go) and don't update them since I'm worried about stability or breaking things. If that's the case, I might checkout the new version for sure.

Thanks again for all your support. I sincerely do appreciate it!
