### ISSUE TITLE
How to use proxies in this?

### ISSUE THREAD

**Issue by myur4** [playwright-community/playwright-go#270]
I can't use proxies since the library itself is apparently negligencing it's own settings.

```Cannot use 'playwright.BrowserTypeLaunchOptionsProxy{Server: playwright.String("my.proxy.ip:port")}' (type playwright.BrowserTypeLaunchOptionsProxy) as the type *BrowserTypeLaunchOptionsProxy```

I'm pretty "new" to Golang, and I'm having no issues with any other headless browser managers when it comes to proxy settings, at all. I hope it's a failure from me, not from the project, since I like everything I saw in the lib.

**Comment by masaushi** [comment]
It seems you should use pointer type of `playwright.BrowserTypeLaunchOptionsProxy`, so please try adding `&` prefix like `&playwright.BrowserTypeLaunchOptionsProxy{Server: ...}` to pass the pointer.

**Comment by myur4** [comment]
Oh, thank you. It worked fine.
