### ISSUE TITLE
[bug/issue] Locator option Has does not work correctly

### ISSUE THREAD

**Issue by sttaran** [playwright-community/playwright-go#274]
I have 2 points about locators.

1. When we create new Locator using Page we can pass PageLocatorOptions. But now if we pass Has option it does not work correctly and returns an error  with message "Malformed token".

For example, this code will return the error because of wrong selector concatenation. 
 
```
  inputLocator, err := page.Locator("input[name='some']")
  require.NoError(t, err)

  listLocator, err := page.Locator("ul", playwright.PageLocatorOptions{Has: inputLocator})
  require.NoError(t, err)

   text, err := listLocator.InnerText()
```

2. The Locator.Locator method does not have a LocatorLocatorOptions parameter. It would be very useful to add the ability to use this option

**Comment by ninadingole** [comment]
If this issue is fixed, I would close it ✌🏻
