### ISSUE TITLE
How to run playwright-go on Ubuntu Server (Headless)

### ISSUE THREAD

**Issue by gunnrcrakr** [playwright-community/playwright-go#277]
Please do step-by-step tutorial 🫡

**Comment by mxschmitt** [comment]
1. Use an Ubuntu 20 image
2. Follow the installation from the readme (playwright install --with deps)

Then it should work!

**Comment by gunnrcrakr** [comment]
> 1. Use an Ubuntu 20 image
> 2. Follow the installation from the readme (playwright install --with deps)
> 
> Then it should work!

Can use without docker ?

**Comment by mxschmitt** [comment]
Yes sure, if it's Ubuntu 20 or 18!

**Comment by gunnrcrakr** [comment]
No worry I made it! Thanks

How to use Playwright on Ubuntu Serverless

1. Launch instance (Ubuntu 20)
2. Install golang (https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-20-04)
3. go get github.com/playwright-community/playwright-go
4. go run github.com/playwright-community/playwright-go/cmd/playwright install --with-deps
5. build main.go then should WORKED! 🦾
