### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by sentinelb51** [playwright-community/playwright-go#280]
![image](https://user-images.githubusercontent.com/75678325/173854157-582bac3b-7fea-4ac0-aad7-a2d3572d1269.png)
I seem to get this issue when trying to install dependencies using the following command:
`go run github.com/playwright-community/playwright-go/cmd/playwright install --with-deps`

I am on Debian.

**Comment by mxschmitt** [comment]
Debian is not supported, only Ubuntu 18 and 20 as of today.

**Comment by Baiyuetribe** [comment]
please add centos surpport
