### ISSUE TITLE
Does playwright-go has Stealth Mode support built-in?

### ISSUE THREAD

**Issue by NuLL3rr0r** [playwright-community/playwright-go#282]
I've just head of Playwright-go and would like to evaluate it. One thing I need badly is Stealth Mode which could be used as Anti-Bot Detectoon similar to [go-rod](https://github.com/go-rod/stealth). I couldn't find anything in the `examples/` folder for Playwright-go.

**Comment by NuLL3rr0r** [comment]
Thank you very much for the snippet.

**Comment by mxschmitt** [comment]
Stealth mode is not in the scope of playwright-go.

**Comment by markthethomas** [comment]
ty for the stealth scripts rec! This solved my exact issue. 🙌

**Comment by tejaskumark** [comment]
@jdfergason Thanks for posting this solution, can you please help me with `stealth.JS` file URL or some clue around that from where I could get that file? 
Thanks

**Comment by jdfergason** [comment]
It's bundled with [go-rod](https://github.com/go-rod/stealth) or you can get it directly from npm: https://www.npmjs.com/package/puppeteer-extra-plugin-stealth

**Comment by jonfriesen** [comment]
I wrote a small shim to inject an extracted version of the puppeteer stealth script into a `playwright.Page`. It's primitive but works. 

https://github.com/jonfriesen/playwright-go-stealth
