### ISSUE TITLE
Using Content() and SetContent()

### ISSUE THREAD

**Issue by sentinelb51** [playwright-community/playwright-go#283]
I am trying to replace specific text inside the HTML content of the page. To do this, I tried:

```go
content, _ := page.Content() // this is of type playwright.Page
replaced := strings.ReplaceAll(content, "text to be replaced", "the replacement text")
_ = page.SetContent(replaced)
```

When I take a screenshot afterwards, the text seems to remain the same, and whatever is returned from page.Content() is also still the same. I'm not sure how to properly replace content, any ideas?

Note: I'm trying to edit ALL occurrences of a string, without knowing where they will be placed within the document.

**Comment by StanislavTaran** [comment]
HI @sentinelb51! Thanks for the issue! At first glance, this should not be a problem. You can look at examples of use SetContent() in playwright-go tests. 
For example https://github.com/playwright-community/playwright-go/blob/main/tests/page_test.go#L32

If you are still having difficulty, it would be great for you to set an example to reproduce the problem.

**Comment by StanislavTaran** [comment]
> ```go
> networkidle
> ```

Of course. Here you can find details https://playwright.dev/docs/api/class-frame#frame-set-content
