### ISSUE TITLE
Upgrade to Go 1.18

### ISSUE THREAD

**Issue by ninadingole** [playwright-community/playwright-go#291]
Playwright-go uses `go 1.14` and I think we should upgrade it to go.18 or go 1.19. We don't use any of the generic or new things in the release because it could break backward compatibility however upgrading it to the latest version would give us the benefits added to the new version like memory model etc.

We could think about using the generics and have another `v2` implementation of the lib that will be completely based on the new features of golang.

I am creating this issue to start a discussion about what others think of upgrading the module to the latest version

**Comment by canstand** [comment]
This issue seems to be overlooked. I wanted to use the go workspace feature, so I submitted a PR (#350) to upgrade to go 1.19. I chose 1.19 because it is the lowest version that is officially supported.

I think it makes sense to defer the generic to `v2`.
