### ISSUE TITLE
Example crawling stuff on Hacker News retrieves nothing

### ISSUE THREAD

**Issue by wu0h961738** [playwright-community/playwright-go#293]
I got nothing after running example copied from playwright-go, the example crawling the current top voted items from [Hacker News](https://news.ycombinator.com/).
Even though all prerequisites for running have been done and no error shows up as running, the result just outputs nothing.
Anyone happen to the same issue?

**Comment by ninadingole** [comment]
@wu0h961738 do you have any error logs that you could post on this thread? Also, you tried to run an exact copy of the example [here](https://github.com/playwright-community/playwright-go/blob/main/examples/scraping/main.go) right?

**Comment by ninadingole** [comment]
I was able to run it without any problem:

```
go run ./examples/scraping/main.go
1: How the SQLite Virtual Machine Works
2: Albania expelled Iran’s embassy staff over July cyberattack
3: Pypi.org is running a survey on the state of Python packaging
4: WikiHouse – Open source, modular, wood based, zero carbon housing
5: Tell HN: Otter.ai bot recording meetings without consent
6: Show HN: Quake 1 ported to the Apple Watch
7: BigFAT – Backward compatible FAT extension for unlimited file size
8: The YC Summer 2022 Batch
9: Difftastic, the fantastic diff
10: Speculoos-2c: A new potentially habitable earth
11: Understanding gambling addiction (2012)
12: Why Not: From Common Lisp to Julia
13: Hydrogen battery startup says it has $700M order backlog
14: Two philosophers found purpose in the world of work
15: Improved Galileo Time to First Fix
16: A Long-Lost Branch of the Nile Helped in Building Egypt’s Pyramids
17: What the interns have wrought, 2022 edition
18: Is engineering management bullshit?
19: Sundar Pichai hopes to make Google more efficient, hints at potential cuts
20: How Isaac Newton discovered the binomial power series
21: We Are Changing the License for Akka
22: Hydrogen production from the air
23: Handwritten thank you notes increase sales
24: What makes a good REPL? (2017)
25: How radical was Rachmaninoff?
26: A “Critical” Tracking Task for Man-Machine Research (1966) [pdf]
27: Facebook engineers: we have no idea where we keep all your personal data
28: From Common Lisp to Julia
29: Ask HN: Is there a Hacker News for writers?
30: Winding numbers using a Cauchy integral, with WebGL
```

Let me know if there's any error that you get when running the file

**Comment by wu0h961738** [comment]
Hi, Problem has been fixed. I didn't notice the OS dependency installation process which should have been done at the first place.
Would you might reply an another question, that the OS dependency be installed as well on production server before golang program builds and deploys?

**Comment by ninadingole** [comment]
Yes you would need the browser driver dependencies on the platform where you want to run playwright-go without that it will not work
