### ISSUE TITLE
how to send a post request

### ISSUE THREAD

**Issue by kaiceo** [playwright-community/playwright-go#294]
i could not find a method to post  request with args,help..

**Comment by ninadingole** [comment]
@kaiceo what are you trying to achieve, what POST request do you want to send? An API call request?

**Comment by kaiceo** [comment]
i hope to get some value from response by sending url post repuest with args after login account, instead of reading page dom value.

**Comment by kaiceo** [comment]
@ninadingole i saw playwright for js can achieve   by APIRequestContext method

**Comment by ninadingole** [comment]
Currently, Playwright-Go doesn't support that
