### ISSUE TITLE
Add timeout option to `WaitForLoadState()`

### ISSUE THREAD

**Issue by shoamano83** [playwright-community/playwright-go#298]
Hello! First of all, thank you so much for creating and maintaining this library! I use this project to create a simple web crawler.

I noticed that `page.WaitForLoadState()` sometimes gets stuck forever. I know the original playwright library has `options?.timeout?` value. (Reference: https://playwright.dev/docs/api/class-page#page-wait-for-load-state) Can we support the same option in Go library as well?

Thanks!

**Comment by shoamano83** [comment]
FYI, I created a hack in my branch and it seems to be working as expected.
https://github.com/shoamano83/playwright-go/tree/wait_for_load_state_timeout

It has a few caveats though:
* This breaks `Page.WaitForLoadState()` and `Frame.WaitForLoadState()` API signatures.
* Compatibility issues with original library:
  - I put `State` field inside `PageWaitForLoadStateOptions` and `FrameWaitForLoadStateOptions`, but it does not exist in the `options?` field of original playwright library.
  - According to the original library's documentation, a default value should be configured by `browserContext.setDefaultNavigationTimeout(timeout)`, `browserContext.setDefaultTimeout(timeout)`, `page.setDefaultNavigationTimeout(timeout)` or `page.setDefaultTimeout(timeout)`. I did not implement such logic.

**Comment by ninadingole** [comment]
@shoamano83 could you please create a PR with the changes you did? 

The code follows a pattern of options as variadic arguments and the required fields are passed as arguments to the method. In the case of `WaitForLoadState` I believe the state should be a required param along with timeout as optional but that would break the contract. However, if that's the right way to do it then we could consider that

**Comment by shoamano83** [comment]
Sure, I created https://github.com/playwright-community/playwright-go/pull/300.

Regarding options, actually I prefer having `state` variable as mandatory arg and leave `FrameWaitForLoadStateOptions` as it is. My concern is that in the original (JavaScript) API, both `state` and `options` args are optional.
https://playwright.dev/docs/api/class-page#page-wait-for-load-state
So people who came from JavaScript library (like me) may be confused. And yes, it breaks API contract.

**Comment by shoamano83** [comment]
After playing around a little more, I now prefer retrieving whether the function has been timed out or not.

So maybe we can create a new API:
```
WaitForLoadStateWithTimeout(state *LoadState, options ...PageWaitForLoadStateOptions) error
```
and keep current `WaitForLoadState()` API as it is?

**Comment by ninadingole** [comment]
I would go with what you have currently implemented, we cannot follow the exact convention of typescript because golang doesn't support optional with default value in the method signature, so what you have currently implemented is good and makes sense, if the user wants to wait for any other load state event they can provide the state in the option

**Comment by Zermond** [comment]
@ninadingole hi. Could you accept this PR?

**Comment by canstand** [comment]
This feature has been implemented
