### ISSUE TITLE
[Question]Do playwright support alpine OS?

### ISSUE THREAD

**Issue by YeKc1M** [playwright-community/playwright-go#301]
I tried to install playwright in alpine. It said that 'Downloaded driver successfully' but there is a file missing
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/43946959/192929973-28968554-5b61-4e8b-8054-8a6ed89f4f40.png">
What can I do?

**Comment by mxschmitt** [comment]
Alpine is not supported, see here: https://playwright.dev/docs/troubleshooting#windows
