### ISSUE TITLE
could not download driver

### ISSUE THREAD

**Issue by yusong0926** [playwright-community/playwright-go#322]
trying to install the browsers and OS dependencies:
 % playwright install --with-deps     
2022/11/28 16:08:57 could not download driver: could not check if driver is up2date: could not run driver: exit status 1

it seems the baseURL get 404.
	baseURL              = "https://playwright.azureedge.net/builds/driver"

any idea?

**Comment by canstand** [comment]
It's probably a network problem.
Close due to outdated.
