### ISSUE TITLE
arm32v7 error!

### ISSUE THREAD

**Issue by zhouyuyu888** [playwright-community/playwright-go#327]
device:Amlogic S805 OneCloud WS1608
system:Ubuntu 20.04.5 LTS | V20221001-5.15.79-meson-32
go version go1.19.5 linux/arm
execute:
**go get github.com/playwright-community/playwright-go
go run github.com/playwright-community/playwright-go/cmd/playwright install --with-deps**﻿
_Downloading driver to /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000
Downloaded driver successfully
/root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: 3: /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/node: Exec format error
2023/01/25 13:28:29 could not run driver: exit status 126
exit status 1_
how to install ms-playwright-go in arm32?

**Comment by huoxue1** [comment]
You should probably install 32-bit nodejs yourself, and then use a soft link to link to the corresponding location, because the installed nodejs seems to be 64-bit
