### ISSUE TITLE
Browser failed to install using `install --with-deps`

### ISSUE THREAD

**Issue by TheDhejavu** [playwright-community/playwright-go#330]
**Platform details**
 - Linux/UNIX
 - 22.04-amd64-server
 
Using `npx playwright install` seems to work but using `go run github.com/playwright-community/playwright-go/cmd/playwright install --with-deps` fails.

<img width="1372" alt="Screen Shot 2023-02-14 at 12 29 12 PM" src="https://user-images.githubusercontent.com/19678915/218725567-11e9d084-6571-4bc3-b58b-4e248505e76a.png">

**Comment by canstand** [comment]
Close issue that refers an outdated version
