### ISSUE TITLE
Playwright script failing for new versions of Ubuntu

### ISSUE THREAD

**Issue by ppcamp** [playwright-community/playwright-go#348]
Playwright fails to install the dependecies for newer versions of ubuntu (22.04.2 LTS). 

You can check more infos [here](https://github.com/microsoft/playwright/issues/13530).

Currently, I need to use the 20.04.6 version to get the proper packages

**Comment by canstand** [comment]
Now you can try the latest version.

**Comment by ppcamp** [comment]
txs. It seems to be working now!
