### ISSUE TITLE
Version v0.3500.0 pointing to playright.sh file of version v0.2000.1

### ISSUE THREAD

**Issue by pradip90das** [playwright-community/playwright-go#355]
Latest playwright code in v0.3500.0is still pointing to old location of playwright.sh (v0.2000.1)

New code should point to version 1.35.0

Getting below error:

```
could not start driver: fork/exec /root/.cache/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: no such file or directory
```

Its breaking while Launching the browser.

**Comment by canstand** [comment]
Please check your code, even `v0.20000.1` calls `v1.25.2`. 

See `https://github.com/playwright-community/playwright-go/blob/main/run.go#L19`

**Comment by canstand** [comment]
Close issue that refers an outdated version
