### ISSUE TITLE
Issue with Wait methods

### ISSUE THREAD

**Issue by Ash-KODES** [playwright-community/playwright-go#359]
`if _, err := page.Locator(`//input[@id='lastName-input']`).WaitForLoadState({
		state: "visible",
}); `

whats wrong in this piece of code,I want to wait till state becomes visible?
can someone please help?

**Comment by canstand** [comment]
should be
```go
err := page.Locator("//input[@id='lastName-input']").WaitFor(playwright.PageWaitForSelectorOptions{
	State: playwright.WaitForSelectorStateVisible,
})
```
state default to `visible`, so 
```go
err := page.Locator("//input[@id='lastName-input']").WaitFor()
```

`WaitForLoadState` is for page or frame, not element.

**Comment by Ash-KODES** [comment]
thankyou @canstand
