### ISSUE TITLE
How to obtain the latest version?

### ISSUE THREAD

**Issue by today2004** [playwright-community/playwright-go#363]
As the question requires, how can I obtain the latest version? 
I pulled the version using “go get -u github.com/playwright-community/playwright-go”, but using “go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps firefox” the firefox version obtained is still  Firefox 113，ms-playwright-go 1.35.1

**Comment by canstand** [comment]
use git branch `main` for latest commit,   e.g. `go get -u github.com/playwright-community/playwright-go@main`

**Comment by today2004** [comment]
> 使用 git 分支`main`获取最新提交，例如`go get -u github.com/playwright-community/playwright-go@main`

good，think you！
