### ISSUE TITLE
How to set the Python code parameter

### ISSUE THREAD

**Issue by today2004** [playwright-community/playwright-go#364]
How to set the Python code parameter http2、http3、headless？
playwright.firefox.launch(
            firefox_user_prefs={
                "network.http.http2.enabled": True,
                "network.http.http3.enable": True,
            },headless=True）
Thank

**Comment by vvanglro** [comment]
Here: https://pkg.go.dev/github.com/playwright-community/playwright-go#BrowserTypeLaunchOptions

**Comment by today2004** [comment]
> Here: https://pkg.go.dev/github.com/playwright-community/playwright-go#BrowserTypeLaunchOptions

Thank you. We found “Headless ”, but we still haven't found “http2” and “http3”
