### ISSUE TITLE
How to specify custom CA certificates

### ISSUE THREAD

**Issue by sirrapa** [playwright-community/playwright-go#371]
Hi,

In the version for Node there is a option to specify an environment variable to configure custom/private CA certificates.
Is there some environment variable when running go?

**Comment by canstand** [comment]
playwright-go supports exactly the same environment variables. **Note** that `NODE_EXTRA_CA_CERTS` only affects the playwright download browser.

Visiting an untrusted certificate site in a browser is another story. Chromium uses the CTL (Certificate Trusted List) of the operating system, and Firefox uses its own CTL that can be started with command line parameters (`--ignore-certificate-errors) to ignore certificate errors.

**Comment by sirrapa** [comment]
Thanks @canstand.

I've got it working now.
