### ISSUE TITLE
Assertions in Go

### ISSUE THREAD

**Issue by ivaylo321** [playwright-community/playwright-go#401]
Hello,

In Javascript I can use syntax like this:

`expect(page.getByTestId('status')).toHaveText('Submitted');`

Is there something similar I can do in Go, instead of 

```
text, err := page.Locator("status").Evaluate("el => el.textContent", nil)
if text != "Submitted" {
    ...
}
```

I am basically asking if there is a way to use the `expect` keyword in Go?

**Comment by tejaskumark** [comment]
I do not think that is available by default, but you can always wrap things up as per your need like this example, `func assertErrorToNilf` https://github.com/playwright-community/playwright-go/blob/main/examples/download/main.go

**Comment by canstand** [comment]
@ivaylo321 you can do this:
```go
expect := playwright.NewPlaywrightAssertions(5000)

err := expect.Locator(page.GetByTestId("status")).ToHaveText("Submitted")

```
