### ISSUE TITLE
Ways to pass context from one browser instance to another

### ISSUE THREAD

**Issue by dbelozerovx1** [playwright-community/playwright-go#414]
Didn't find Questions tab in this repo so ill ask it here i guess

Is there any way to pass context from one playwright.Browser instance to another? Besides browser.NewContext(BrowserNewContextOptions{}), because state from ctx.StorageState() from browser is StorageState type, and for NewContext is OptionalStorageState and nested Cookie is also different types, its so frustrating, i think its not intended to work like this, manually build context every time doesnt seem okay for me

any suggestions, maybe im blind and cant see an easy way to solve my problem?

**Comment by canstand** [comment]
try share storage state with file:
```go
storageFile := "storage.json"

sharedBrowserContextOption := playwright.BrowserNewContextOptions{}

ctx1, _ := browser.NewContext(sharedBrowserContextOption)

ctx1.StorageState(storageFile)  // save storage

sharedBrowserContextOptions.StoragePath = playwright.String(storageFile)

// reuse ctx options
ctx2, _ := browser.NewContext(sharedBrowserContextOptions)

```

**Comment by dbelozerovx1** [comment]
that is one way but not actually what im trying to do, here some context, i need to pass context with storageState from one browser that did some logins/auth to new another browser so the new browser will has same sessions and wont need to login/auth to apps again
