### ISSUE TITLE
Secured Cookies

### ISSUE THREAD

**Issue by dbelozerovx1** [playwright-community/playwright-go#430]
Is there any way to retrieve secured cookies, i can grab cookies stored in context.StorageState, which also has secure(bool) flag but it doesnt make sense if only non-secured cookies are shown, did i mess up somewhere? it just doesnt shown, works on every website with cookie based auth 

upd: a bit not clear, my bad, cookies like sessionid, authcode, etc... anything that website is using for cookie based auth not shown in playwright instance, but with my regular browser i can spot it with zero problems

**Comment by canstand** [comment]
`browserContext.Cookies()` can get all cookies, include secure cookie. But there is an edge case in my test, **webkit** only works when using **https**.
