### ISSUE TITLE
Can't change user-agent on headless mode

### ISSUE THREAD

**Issue by qphuongl** [playwright-community/playwright-go#448]
Hi, I tried to change UserAgent while running headless mode to avoid HeadlessChrome, but it was not working; here is my config:

- `BrowserTypeLaunchOptions`:
```
Args: ["--disable-extensions","--disable-images","--window-size=1920,1080","--start-maximized", "--headless=new"]
HandleSIGUP, HandleSIGINT, HandleSIGTERM: false
IgnoreDefaultArgs: ["--enable-automation","--no-sandbox","--mute-audio","--headless","--disable-features"]
```

_I ignored the default `--headless` flag because I want to use --headless=new to access chrome://version after trying --headless (failed)._

- `BrowserNewContextOptions` 
```
UserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
```

Actually, I tried to change userAgent in both headless and head mode but it's still not working. But right now, I'm dealing with headless mode. 

Spec:
- Chromium 123.0.6312.4 (Developer Build) (arm64)
- Javascript: V8 12.3.219.1
- OS: macOS version 14.4

**Comment by canstand** [comment]
Can't reproduce it. It worked fine in my test.

```go
func TestHeadlessNew(t *testing.T) {
	b2, err := browserType.Launch(playwright.BrowserTypeLaunchOptions{
		Headless: playwright.Bool(false),
		Args: []string{
			"--disable-extensions", "--disable-images", "--window-size=1920,1080", "--start-maximized", "--headless=new",
		},
		IgnoreDefaultArgs: []string{"--enable-automation", "--no-sandbox", "--mute-audio", "--headless", "--disable-features"},
	})
	require.NoError(t, err)
	defer b2.Close()
	nCtx, err := b2.NewContext(playwright.BrowserNewContextOptions{
		UserAgent: playwright.String("foobar/1.0"),
	})
	require.NoError(t, err)
	defer nCtx.Close()
	nPage, err := nCtx.NewPage()
	require.NoError(t, err)

	resChan := server.WaitForRequestChan("/empty.html")
	_, err = nPage.Goto(server.PREFIX + "/empty.html")
	require.NoError(t, err)
	res := <-resChan
	require.True(t, strings.HasPrefix(res.Header.Get("User-Agent"), "foobar"))
}
```

**Comment by func25** [comment]
Thanks @canstand, here is my code to create the browser context:

```go
func newChromeContext(savePath string) (playwright.BrowserContext, error) {
	if global.chromeDefault == nil {
		return nil, errors.New("chrome is not initialized")
	}

	browser := *global.chromeDefault

	opts := playwright.BrowserNewContextOptions{}
	opts.UserAgent = playwright.String("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36")
	if savePath != "" && isFileExist(savePath) {
		opts.StorageStatePath = playwright.String(savePath)
	}

	context, err := browser.NewContext(opts)
	if err != nil {
		return nil, fmt.Errorf("create new browser context: %w", err)
	}

	return context, nil
}

```

And the screenshot that is taken programmatically when I open chrome://version shows that the version still has 'headless'

![2024-06-22 10:14:54 204869 +0700 +07 m=+41 120290085](https://github.com/playwright-community/playwright-go/assets/39565248/feed6733-110b-4e45-a124-be41abfbbdf6)

**Comment by qphuongl** [comment]
Thanks @canstand, here is my code to create the browser context:

```go
func newChromeContext(savePath string) (playwright.BrowserContext, error) {
	if global.chromeDefault == nil {
		return nil, errors.New("chrome is not initialized")
	}

	browser := *global.chromeDefault

	opts := playwright.BrowserNewContextOptions{}
	opts.UserAgent = playwright.String("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36")
	if savePath != "" && isFileExist(savePath) {
		opts.StorageStatePath = playwright.String(savePath)
	}

	context, err := browser.NewContext(opts)
	if err != nil {
		return nil, fmt.Errorf("create new browser context: %w", err)
	}

	return context, nil
}

```

And the screenshot that is taken programmatically when I open chrome://version shows that the version still has 'headless'

![2024-06-22 10:14:54 204869 +0700 +07 m=+41 120290085](https://github.com/playwright-community/playwright-go/assets/39565248/feed6733-110b-4e45-a124-be41abfbbdf6)

**Comment by canstand** [comment]
Playwright does not modify the useragent via cli arguments, so the useragent shown in the screenshot is not the same as the request sent when using it.

Also, while digging into this I found an environment variable `PLAYWRIGHT_CHROMIUM_USE_HEADLESS_NEW`.
Use it to avoid using the cli args.

[`https://github.com/microsoft/playwright/packages/playwright-core/lib/server/chromium/chromium.js`](https://github.com/microsoft/playwright/blob/d74ddaebe74c36457428567ca912154f1715dbb2/packages/playwright-core/src/server/chromium/chromium.ts#L319)

**Comment by qphuongl** [comment]
Thank you for your help and suggestion; the issue has been resolved. The problem was due to misunderstanding how Playwright handles UserAgent.
