### ISSUE TITLE
[Bug]: hardwareConcurrency  is limited to 4

### ISSUE THREAD

**Issue by twolao** [playwright-community/playwright-go#451]
**Environments**

- playwright-go Version: [e.g. v0.4201.1]   
- Browser: [e.g. firefox]
- OS and version: [e.g. macOS / Windows 11/ Ubuntu 22.04]

**Bug description**

hardwareConcurrency is limited to 4. No relevant settings are seen in the code. It cannot be modified using javascript in the started browser.
https://browserleaks.com/javascript

How can to modify and adjust hardwareConcurrency setting?

**To Reproduce**
Please provide a mini reproduction rather than just a description. For example:

**Additional context**

**Comment by canstand** [comment]
You mean [this](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency)? It's read-only and depends on environment.

>The `navigator.hardwareConcurrency` **read-only** property returns the number of logical processors available to run threads on the user's computer.
