### ISSUE TITLE
[Feature]: Support create Playwright instance without install driver or specify executable path

### ISSUE THREAD

**Issue by g-a-r-y** [playwright-community/playwright-go#478]
**Does the upstream have similar features?**
yes

**Is your feature request related to a problem? Please describe.**
My scenarios is open browser by other way not playwright, then connect the broswer by cdp

With the python version, I can create playwright instance and connect over cdp:
`pw = sync_playwright().start()`
`browser = pw.chromium.connect_over_cdp(f"http://127.0.0.1:{port}", timeout=5000)`
But with this client, it seems necessary to install driver and browsers

**Describe the solution you'd like**
Can I just connect the browser with cdp, thanks

**Comment by canstand** [comment]
Driver is required. playwright-python just installs it during pip. 

You can install just the driver from the command line: #340 

Or install it yourself:
```go
driver, _ := playwright.NewDriver(playwright.RunOptions{ SkipInstallBrowsers: true })
err := driver.Install()
```

**Comment by g-a-r-y** [comment]
> Driver is required. playwright-python just installs it during pip.
> 
> You can install just the driver from the command line: #340
> 
> Or install it yourself:
> 
> ```go
> driver, _ := playwright.NewDriver(playwright.RunOptions{ SkipInstallBrowsers: true })
> err := driver.Install()
> ```

ok, thanks for the reply. It would be nice if the official support the feature
