### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Xiaomajohn** [playwright-community/playwright-go#483]
Why does the use-local-chrome in the example also have the following code for the playwright.install？

![image](https://github.com/user-attachments/assets/dc0dfe74-af48-40b9-88fd-b7421efc5561)

He downloaded the browser driver from the Internet

![image](https://github.com/user-attachments/assets/867b5646-342c-40b8-a384-96d1cca65585)

**Comment by canstand** [comment]
https://github.com/playwright-community/playwright-go/issues/478#issuecomment-2257352537
