### ISSUE TITLE
[Bug]: could not start playwright: please install the driver (v1.47.0) and browsers first: %!w(<nil>) when trying to run on CloudRun

### ISSUE THREAD

**Issue by lukackaadam** [playwright-community/playwright-go#486]
**Environments**

- playwright-go Version: github.com/playwright-community/playwright-go v0.4700.0  
- Browser: any
- OS and version: macOS 

**Bug description**

Hi, I am running golang project which uses playwright. Everything works locally and I can use playwright and it installs and run Browser and gets to URL no problem
- running this in docker container 
To build locally I use
- `docker build -t api:1 .`
- `docker run -d -p 8080:8080 api:1`
- then I can make requests to my go backend which runs playwright 

Problem is when I deploy this to Google Cloud Run
- `docker build -t gcr.io/my-project/api:1 .`
- `docker push gcr.io//my-project/api:1`
- `gcloud run deploy --image gcr.io//my-project/api:1 --platform managed`

this deploys my api and API works fine. the problem is that when I make a request to my resolver where I start playwright 
```
pw, err := playwright.Run()
	if err != nil {
		log.Printf("could not start playwright: %v", err)
		return nil, errors.New("Error contact support.")
	}
```

I get this error back `could not start playwright: please install the driver (v1.47.0) and browsers first: %!w(<nil>)`

**To Reproduce**
Steps above in bug description

**Go project setup**
My setup is golang + graphql
- my resolver is in `gql-user` folder 
- function name is `func (r *Resolver) GetTestData(p graphql.ResolveParams) (interface{}, error) {`
- import is `"github.com/playwright-community/playwright-go"`
- I am using docker file https://github.com/playwright-community/playwright-go/blob/main/Dockerfile.example with go version 1.22.1

As I mentioned this works fine locally but as soon as I push the container to Cloud Run I am getting the error that `could not start playwright: please install the driver (v1.47.0) and browsers first: %!w(<nil>)`

**Comment by canstand** [comment]
Maybe the version in `go.mod` is not `v0.4700.0` **when you build** the container image? A rebuild is required every time the playwright-go major or minor version number is updated.

**Comment by lukackaadam** [comment]
it was couple things
- node not being installed in docker container on cloud run, (local docker had to use some cached version probably)
- then another thing was that I have not done this on my app start 
```
if err := playwright.Install(&playwright.RunOptions{
		Browsers: []string{"chromium"},
		// DriverDirectory:     "/tmp/playwright",
		SkipInstallBrowsers: false,
		Verbose:             true,
	}); err != nil {
		log.Fatalf("could not install playwright here: %v", err)
	}
```

As I thought it will be handled by docker file but how wrong I was.
