### ISSUE TITLE
[Feature]: Allow us to set the full path to cli js (driver)

### ISSUE THREAD

**Issue by hmajid2301** [playwright-community/playwright-go#496]
**Does the upstream have similar features?**

I don't know, this is a code-specific feature request. Please let me know if I should request is there.

**Is your feature request related to a problem? Please describe.**

This is probably a very niche use case of this library. I am using Nix to set up my development environment (and also NixOS). I have set up playwright using this flake, https://github.com/pietdevries94/playwright-web-flake.

 The cli.js is then made available at this path: `/nix/store/l15bkcb7w90zm1h08qbdq9fc0ssf7sg4-_at_playwright_slash_test-1.47.2/lib/node_modules/@playwright/test/node_modules/playwright-core/cli.js` (for example)

As you can see, with the current code in `run.go` and the `getDriverCliJs` function, it expects it to be within the package. 

**Describe the solution you'd like**

Would it be possible to maybe set an environment variable or an option to allow us to hardcode this? 

Default to this, or allow us to set the path in the constructor? I guess this would make the code a bit more complex. But just a thought. 

```
filepath.Join(driverDirectory, "package", "cli.js")
```

**Additional context**

Nix the package manager expects things to be installed differently to a lot of other package managers, so hence this is an issue for me using it. 

Thanks in advance

**Comment by hmajid2301** [comment]
@canstand Thank you for all the work on the PR, however I don't think it solves my exact issue. I have a path like so generated from the nix flake i am using to setup playwright `/nix/store/91di90vq53hgpl1y3jxkhdk1jikcscdw-_at_playwright_slash_test-1.48.2/lib/node_modules/@playwright/test` and inside this folder I have the following; 

```
Permissions  Size User Group Date Modified Name
dr-xr-xr-x      - root root   1 Jan  1970   .
dr-xr-xr-x      - root root   1 Jan  1970   ..
dr-xr-xr-x      - root root   1 Jan  1970   node_modules
.r-xr-xr-x    757 root root   1 Jan  1970   cli.js
.r--r--r--    679 root root   1 Jan  1970   index.d.ts
.r--r--r--    648 root root   1 Jan  1970   index.js
.r--r--r--    679 root root   1 Jan  1970   index.mjs
.r--r--r--   11Ki root root   1 Jan  1970   LICENSE
.r--r--r--    254 root root   1 Jan  1970   NOTICE
.r--r--r--  1.2Ki root root   1 Jan  1970   package-lock.json
.r--r--r--    778 root root   1 Jan  1970   package.json
.r--r--r--  8.0Ki root root   1 Jan  1970   README.md
.r--r--r--    650 root root   1 Jan  1970   reporter.d.ts
.r--r--r--    645 root root   1 Jan  1970   reporter.js
.r--r--r--    645 root root   1 Jan  1970   reporter.mjs
```

I need a way to be able to specify the `cli.js` inside this folder however the library still expects cli to be in package/cli.js. If that makes sense. I can do a PR to allow us to specify the full path ? Else if this is out of scope of this project I will to try work something else out ?

**Comment by hmajid2301** [comment]
Anyone who is using playwright-web-flake, https://github.com/pietdevries94/playwright-web-flake

You can do something like so now: `PLAYWRIGHT_DRIVER_PATH="${pkgs.playwright-driver}"`. In my nix flake dev shell: https://gitlab.com/hmajid2301/banterbus/-/blob/a13215011408af7885feb361176ff6db868ef774/shell.nix#L43-46

Thanks @canstand!!!

**Comment by canstand** [comment]
Happy to help. The PR #501 is aligned with similar behavior of clients like `playright-python/dotnet/java`. If it doesn't work well, I tend to create symbolic links or other generic ways.
