### ISSUE TITLE
[Feature]: Ligther requirement for Install when used with Connect only

### ISSUE THREAD

**Issue by cedric-appdirect** [playwright-community/playwright-go#511]
**Does the upstream have similar features?**
No idea.

**Is your feature request related to a problem? Please describe.**
When using `Connect` to a remote end on a `BrowserType`, you still need to do a full install which is slow and bring a lot of unnecessary dependencies. Would be nice to reduce those needs.

**Describe the solution you'd like**
When doing a **playwright.Playwright**.**playwright.BrowserType**`.Connect`, we still need to do a `playwright.Install` and `playwright.Run` which bring requirement on the install. Ideally, we should be able to connect with no local requirement at all.

**Additional context**

**Comment by canstand** [comment]
#478
